import Head from 'next/head'
import s from '@styles/landing-page.module.scss';
import Dashboard from './dashboard';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="[ckeditor-build-path]/ckeditor.js"></script>
      </Head>
      <main className={s.main}>
        <Dashboard />
      </main>
    </>
  )
}
